### ISSUE TITLE
What is the minimum efficient configuration for Asp.Net Core Vue Project (for Vs.Net)

### ISSUE THREAD

**Issue by glikoz** [SoftwareAteliers/asp-net-core-vue-starter#10]
I prepared my solution 7 months ago, I thinks some improvements happened from that time till now. The question is what is the minimum efficient configuration for Asp.Net Core  Vue project. (for Visual Studio. Net, not for Vs Code)
Could I get your project as base. Or am I missing something?

**When I look my webpack.config.vendor.js:**

`const path = require('path')
const webpack = require('webpack')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')

module.exports = () => {
  console.log('Building vendor files for \x1b[33m%s\x1b[0m', process.env.NODE_ENV)

  const isDevBuild = !(process.env.NODE_ENV && process.env.NODE_ENV === 'production')
  const extractCSS = new ExtractTextPlugin('vendor.css')

  return [{
    stats: { modules: false },
    resolve: {
      extensions: ['.js']
    },
    module: {
      rules: [
        { test: /\.(png|woff|woff2|eot|ttf|svg)(\?|$)/, use: 'url-loader?limit=100000' },
        { test: /\.css(\?|$)/, use: extractCSS.extract(['css-loader']) }
      ]
    },
    entry: {
      vendor: ['event-source-polyfill', 'vue', 'vuex', 'axios', 'vue-router', 'jquery']
    },
    output: {
      path: path.join(__dirname, 'wwwroot', 'dist'),
      publicPath: '/dist/',
      filename: '[name].js',
      library: '[name]_[hash]'
    },
    plugins: [
      extractCSS,
      // Compress extracted CSS.
      new OptimizeCSSPlugin({
        cssProcessorOptions: {
          safe: true
        }
      }),
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        Popper: ['popper.js', 'default']
        /* For modal, you will need to add tether */
      }), // Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
      new webpack.DllPlugin({
        path: path.join(__dirname, 'wwwroot', 'dist', '[name]-manifest.json'),
        name: '[name]_[hash]'
      }),
      new webpack.DefinePlugin({
        'process.env.NODE_ENV': isDevBuild ? '"development"' : '"production"'
      })
    ].concat(isDevBuild ? [] : [
      // new webpack.optimize.UglifyJsPlugin()
    ])
  }]
}
`

**and "webpack.config.js":**

`const path = require('path')
const webpack = require('webpack')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')
const bundleOutputDir = './wwwroot/dist'

module.exports = () => {
  console.log('Building for \x1b[33m%s\x1b[0m', process.env.NODE_ENV)

  const isDevBuild = !(process.env.NODE_ENV && process.env.NODE_ENV === 'production')
  const extractCSS = new ExtractTextPlugin('site.css')

  return [{
    stats: { modules: false },
    entry: { 'main': './ClientApp/boot-app.js' },
    resolve: {
      extensions: ['.js', '.vue'],
      alias: isDevBuild ? {
        'vue$': 'vue/dist/vue',
        'components': path.resolve(__dirname, './ClientApp/components'),
        'views': path.resolve(__dirname, './ClientApp/views'),
        'utils': path.resolve(__dirname, './ClientApp/utils'),
        'api': path.resolve(__dirname, './ClientApp/store/api')
      } : {
          'components': path.resolve(__dirname, './ClientApp/components'),
          'views': path.resolve(__dirname, './ClientApp/views'),
          'utils': path.resolve(__dirname, './ClientApp/utils'),
          'api': path.resolve(__dirname, './ClientApp/store/api')
        }
    },
    output: {
      path: path.join(__dirname, bundleOutputDir),
      filename: '[name].js',
      publicPath: '/dist/'
    },
    module: {
      rules: [
        { test: /\.vue$/, include: /ClientApp/, use: 'vue-loader' },
        { test: /\.js$/, include: /ClientApp/, use: 'babel-loader' },
        { test: /\.css$/, use: isDevBuild ? ['style-loader', 'css-loader'] : ExtractTextPlugin.extract({ use: 'css-loader' }) },
        { test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' },
        { test: /\.(woff|woff2|eot|ttf|otf)$/, loader: 'file-loader' },
        {
          test: /\.js$/,
          exclude: /node_modules(?!\/quill-image-drop-module|quill-image-resize-module)/,
          loader: 'babel-loader'
        }
      ]
    },
    plugins: [
      new webpack.ProvidePlugin({
        'window.Quill': 'quill',
      }),
      new webpack.DllReferencePlugin({
        context: __dirname,
        manifest: require('./wwwroot/dist/vendor-manifest.json')
      })
    ].concat(isDevBuild ? [
      // Plugins that apply in development builds only
      new webpack.SourceMapDevToolPlugin({
        filename: '[file].map', // Remove this line if you prefer inline source maps
        moduleFilenameTemplate: path.relative(bundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
      })
    ] : [
        // Plugins that apply in production builds only
        //new webpack.optimize.UglifyJsPlugin(),
        extractCSS,
        // Compress extracted CSS.
        new OptimizeCSSPlugin({
          cssProcessorOptions: {
            safe: true
          }
        })
      ])
  }]
}
`

**Comment by liborpansky** [comment]
Hi, I guess you used template made by TrilonIO you can found [at the following link](https://github.com/TrilonIO/aspnetcore-Vue-starter).
I used this template before CLI 3.0+ and it's exactly the reason I created this template, so you do not have to use webpack configuration files for vendor and application, set uglify and optimization plugins, and just scaffold a new project with a single command which works with Vue CLI and Webpack with no configuration at all (configuration is set by vue team under the hood).

I also updated all "legacy" company projects to a new Vue CLI 3 project structure and I have to say I'm really satisfied with result with no configuration and everything working just as you would expect without ever touching webpack config files.

**Comment by glikoz** [comment]
Thanks a lot for your great work.
