### ISSUE TITLE
Auth0

### ISSUE THREAD

**Issue by julian-code** [SoftwareAteliers/asp-net-core-vue-starter#12]
Hey liborpansky.

Thanks for this awesome template.

I really want to explore Vue and ASP.net core with Auth0. However, I have struggle to make Auth0 work properly with this template.

Do you know, how to set it up? Do I need to configure it in my Vue app or at ASP.net core level? 

Have a nice day :-)

**Comment by liborpansky** [comment]
Hi, personally I've never used Auth0 - I prefer to use [Identity Server 4](https://github.com/IdentityServer/IdentityServer4), which offers you the same features (JWT / OAuth 2.0/ OpenID Connect), but it's hosted by you without paying for authentication as a service...

Anyway, logic is the same for both IS4 and Auth0 - you have to authenticate your users from vue app redirecting them to SSO server and get back access token and save to to a vue app. Then you use this token (send in HTTP Authentication Header) to communicate with API.

So the implementation you have to do has two parts:

- Client implementation - use [oidc client](https://github.com/IdentityModel/oidc-client-js) or [auth0-js](https://github.com/auth0/auth0.js) to resolve authority server and redirect user to SSO server and save access token on redirect back
- Server implementation - apply JWT or OWIN authentication middleware to ASP.NET Core API to validate incomming token

I suggest you to check Identity Server Documentation or Auth0 documentation, it's really detailed and explains everything...

[Vue app Identity Server](http://docs.identityserver.io/en/latest/quickstarts/6_javascript_client.html)
[Vue app Auth0](https://auth0.com/docs/quickstart/spa/vuejs)
[ASP.NET Core API Identity Server](http://docs.identityserver.io/en/latest/topics/apis.html)
[ASP.NET Core API Auth0](https://auth0.com/docs/quickstart/backend/aspnet-core-webapi)

Good luck!

**Comment by julian-code** [comment]
Hey @liborpansky. 

Very nice answer and quick reply. Really appreciate it.
