### ISSUE TITLE
tsconfig.json should be Content, not None.

### ISSUE THREAD

**Issue by FrikkinLazer** [SoftwareAteliers/asp-net-core-vue-starter#14]
In VS2019 I was getting:

`TS1219: Experimental support for decorators is a feature that is subject to change in a future release`

Changing tsconfig.json to Content solved the problem.

**Comment by liborpansky** [comment]
I actually never use VS for client-side development so I haven't noticed it before, thanks for the heads up!

**Comment by FrikkinLazer** [comment]
No problem keep up the good work.
