### ISSUE TITLE
Migrate project to ASP.NET Core 3.0

### ISSUE THREAD

**Issue by liborpansky** [SoftwareAteliers/asp-net-core-vue-starter#16]
Migrate project to ASP.NET Core 3.0 and update template to a new SPA template.
Update VueCliMiddleware to 3.0 (now in preview) and test the middleware out.

**Comment by liborpansky** [comment]
30e4baf5b0c03b45e2a83508d6680844ff0d82f9

**Comment by liborpansky** [comment]
https://github.com/SoftwareAteliers/asp-net-core-vue-starter/commit/30e4baf5b0c03b45e2a83508d6680844ff0d82f9

**Comment by FF128** [comment]
I love your work @liborpansky! It is a great template for asp.net core and vuejs developers. Cheers!
