### ISSUE TITLE
netcore3.0 version - how access razor page?

### ISSUE THREAD

**Issue by dotnetshadow** [SoftwareAteliers/asp-net-core-vue-starter#18]
Hi there,

I know that the 3.0 version isn't final yet, so I'm testing your 3.0 branch.
When using **v2.2** navigating to `http://localhost:5000/error` I get the error page from razor which is correct

If I use **v3.0** and I navigate to `http://localhost:5000/error` I get a blank page
Is this a known issue in the 3.0 version?

**Comment by dotnetshadow** [comment]
Fixed by adding: 

**ConfigureServices**
`services.AddRazorPages();`

**Configure()**
`endpoints.MapRazorPages();`

**Comment by liborpansky** [comment]
Hi, thanks for the heads up!

Strange thing is, that the official Microsoft template for .NET Core 3.0 does not contain Razor pages, I've respected the structure precisely. Maybe the error handling with Razor pages does not work for then either?
