### ISSUE TITLE
Vue CLI 3 pull request was merged

### ISSUE THREAD

**Issue by alexsandro-xpt** [SoftwareAteliers/asp-net-core-vue-starter#2]
The pull request  https://github.com/aspnet/JavaScriptServices/pull/1726 was merged how long will be ready to user for us?

**Comment by liborpansky** [comment]
The pull request https://github.com/aspnet/JavaScriptServices/pull/1726 is still open and waiting to be accepted and merged by aspnet team.

**Comment by dotnetter** [comment]
Hi,

What's the timescale for this?

Regards,

Wayne

**Comment by liborpansky** [comment]
You should ask Microsoft guys in a JavaScriptServices repository at https://github.com/aspnet/JavaScriptServices

**Comment by liborpansky** [comment]
@SteveSandersonMS wrote:

> As far as I'm aware, we don't have plans to introduce Vue-specific features. This isn't because we have anything against Vue, but rather just to limit the growth in the number of frameworks that we're maintaining support for. The dev team only has a finite capacity for handling third-party concepts, and last year we made the strategic choice to focus on only Angular and React.

@EEParker published ASP.NET Core Vue CLI middleware as a separate extension nuget package available at:
https://github.com/EEParker/aspnetcore-vueclimiddleware
https://www.nuget.org/packages/VueCliMiddleware/2.1.1

Middleware has been installed to the starter template, you can clone a new version with a full Vue support.
