### ISSUE TITLE
task.json out of date? 

### ISSUE THREAD

**Issue by NickStees** [SoftwareAteliers/asp-net-core-vue-starter#20]
```
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\git\asp-net-core-vue-starter/asp-net-core-vue-starter.csproj
```

New to .NET tried to get this running but get an error after a fresh clone and running `dotnet run` in VScode.

**Comment by liborpansky** [comment]
Hi, thanks for the PR!

Maybe it's better to re-create the launch.json configuration for Web Launch? I noticed there are some changes with the current version (at least how VS Code generates it):
```
{
      "name": ".NET Core Launch (web)",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build",
      "program": "${workspaceFolder}/bin/Debug/netcoreapp3.0/AspNetCoreVueStarter.dll",
      "args": [],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
      "serverReadyAction": {
        "action": "openExternally",
        "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)"
      },
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "sourceFileMap": {
        "/Views": "${workspaceFolder}/Views"
      }
    }
```

I don't use this configuration, can you try it eventually?

Other files modified:

- tasks.json :thumbsup:
- ClientApp/package.json - I wouldn't change it, it's against best practices (also VS gives you a warning `String does not match the pattern of "^(?:@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*$"`)
- ClientApp/public/manifest.json - same situation as package.json
- SoftwareAteliers.AspNetCoreVueStarter.nuspec - project URL is not correct, previous version https://github.com/SoftwareAteliers/asp-net-core-vue-starter is correct
