### ISSUE TITLE
Authentication & Authorization like React template

### ISSUE THREAD

**Issue by gopala000** [SoftwareAteliers/asp-net-core-vue-starter#25]
Are there any guidance on how to build authentication and authorization for a SPA like what comes with React & Angular project templates?

**Comment by tvkit** [comment]
The closest I came so far:  [Authentication and authorization for SPAs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0)

In the past, I relied on the Router to require authentication. Perhaps a Vuex state could be used to hold the authentication state.

**Comment by liborpansky** [comment]
Hi, there's already been a [question](https://github.com/SoftwareAteliers/asp-net-core-vue-starter/issues/12) about auth integration with Vue app with external auth provider (Auth0, Identity Server).

I use generally oidc-client with [vuex-oidc](https://github.com/perarnborg/vuex-oidc), where you can see integration between authentication (in this case SSO server and oidc-client, but it can be generic auth provider) and Vue router and Vuex. On [wiki page](https://github.com/perarnborg/vuex-oidc/wiki) you can find all the information.

Good luck!

**Comment by gopala000** [comment]
Thanks for your replies. I ended up porting the react components to vue from the app created by VS 2019 react project. Core of their authorization code is a JavaScript wrapper over oidc-client npm package. I reused it without making any changes.

**Comment by FF128** [comment]
@gopala000 You should try JWT Authentication. Check this tutorial https://jasonwatmore.com/post/2018/08/14/aspnet-core-21-jwt-authentication-tutorial-with-example-api
