### ISSUE TITLE
Waiting for update signal from WDS / websocket closed before connection established

### ISSUE THREAD

**Issue by jason-e-gross** [SoftwareAteliers/asp-net-core-vue-starter#26]
![image](https://user-images.githubusercontent.com/16501884/70133235-50ab8e00-164b-11ea-916d-5eab915e3259.png)

When HMR tries starting, this message shows up in the console -- and there's no socket connection.   The first websocket network call says its switching protocols 

![image](https://user-images.githubusercontent.com/16501884/70133458-c1eb4100-164b-11ea-8f72-28aa18a20daa.png)

then the second one produces the error, and right after is some xhr_streaming network call.

**Comment by liborpansky** [comment]
Hi, I wasn't able to reproduce the issue on Google Chrome 79 on Windows. 😞 
There are [similar issues](https://github.com/sockjs/sockjs-client/issues/353) regarding socketjs-client disconnections, so you're not alone...
