### ISSUE TITLE
Asp.net Core 2.1 and VueCliMiddleware 2.1 

### ISSUE THREAD

**Issue by Ethan0007** [SoftwareAteliers/asp-net-core-vue-starter#3]
Hi,

I just want to share something on my development issue, i have asp.net core 2.1 and and using vue cli 3, I'm having issue when start debugging of the project and the issue is not consistent sometimes it work and sometimes it fails. please see screenshot below:

![image](https://user-images.githubusercontent.com/12542052/49491986-feddf580-f888-11e8-877d-0084f195b32c.png)

Thanks

**Comment by liborpansky** [comment]
Hi,
thanks for the report. 

I noticed the issue and it's a problem connected with [VueCliMiddleware](https://github.com/EEParker/aspnetcore-vueclimiddleware) and probably with [JavaScriptServices](https://github.com/aspnet/JavaScriptServices). When Vue CLI Middleware calls JavaScriptServices NpmScriptRunner, a new npm process is started. If you run your application in a console (not IIS Express), you can notice the console with ASP.NET Core and npm remains opened. If you try to start your app second time, a second instance of npm process is started and Vue CLI Middleware does not recognize the process is running and after 50 seconds of timeout throws the exception you encountered.

I'm not sure how React or Angular CLI handles this problem, if the timeout happens also for these CLI middlewares - I haven't gather enough information yet to open an issue for VueCliMiddleware repository.

For this reason I prefer during development a Proxy to SPA Development server middleware using `spa.UseProxyToSpaDevelopmentServer("http://localhost:8080");` function in Startup file. I just run an instance of client app in separate console / VS Code before by `npm start serve` command, keep it running and then start the ASP.NET Core app with UseProxyToSpaDevelopmentServer.

**Comment by Ethan0007** [comment]
Hi @liborpansky ,

Thank you for the reply. Yes you are right when server is rebuild js also rebuild. I have a workaround of this issue in my development mode i just add some line of codes(see image below). You can start server side debugging.  Just need to to "npm run build".

![image](https://user-images.githubusercontent.com/12542052/49576149-fcf26000-f976-11e8-8d01-6abd49af0080.png)

**Comment by Ethan0007** [comment]
Hi @liborpansky,

I just want to share and ask something when adding route parameter, how can i exclude the route-name in the Request Url because it will create an issue when in ajax-call.

I'm using axios: 0.18

![image](https://user-images.githubusercontent.com/12542052/49683887-546f0800-fafe-11e8-8b42-6ac7ec029a45.png)

Thank you.

**Comment by Ethan0007** [comment]
Hi,

I already solved the issue by adding attribute in the controller.
like:
[Route(“test/api/[controller]”)]
