### ISSUE TITLE
Avast identifies IDP.Generic threat in AspNetCoreVueStarter.exe

### ISSUE THREAD

**Issue by joffff** [SoftwareAteliers/asp-net-core-vue-starter#30]
When running the latest release (2.3.2), Avast identifies a threat in `bin/Debug/netcoreapp3.1/AspNetCoreVueStarter.exe` as IDP.Generic.

Is this expected behaviour?

**Comment by liborpansky** [comment]
Hi, what a strange behaviour! It's actually almost default .NET Core app based on Microsoft template with VueCliMiddleware installed fro NuGet. 
Do you have the same experience with default .net projects and/or React and Angular SPA templates integrated in Visual Studio?

**Comment by joffff** [comment]
I'm not overly familiar with the world of .NET so I'm not best placed to answer that.  😕  The only other .NET Core project I've got is the ASP.NET Core 2.2 version of this repo (release [1.1.0](https://github.com/SoftwareAteliers/asp-net-core-vue-starter/releases/tag/1.1.0) which doesn't raise any Avast errors when running.

I only attempted release 2.3.2 during investigation into another issue.
