### ISSUE TITLE
sign in pop up when run project

### ISSUE THREAD

**Issue by kenghot** [SoftwareAteliers/asp-net-core-vue-starter#32]
![image](https://user-images.githubusercontent.com/4973052/76683069-9d800700-6633-11ea-9581-d41a9df72a61.png)
I've cloned repository and run project by using vs2019 then the pop up windows  show up and ask me to sign in. What should i do ?

**Comment by liborpansky** [comment]
Hi, it looks like your IIS Express site settings has basic authentication on. Default behaviour should be Anonymous Authentication with no restrictions.
Check project properties in Debug section:
![image](https://user-images.githubusercontent.com/9642342/76686868-2a6c9580-661f-11ea-92f8-208bf1823dfc.png)

**Comment by kenghot** [comment]
![image](https://user-images.githubusercontent.com/4973052/76693312-79eda880-6695-11ea-8840-9acf94842c49.png)
Hi liborpansky , this is my debug setting
