### ISSUE TITLE
Running in Development mode?

### ISSUE THREAD

**Issue by mattgrande** [SoftwareAteliers/asp-net-core-vue-starter#34]
Hi there, I feel like I'm missing something basic (and I'm pretty  new to the ASP.Net Core world, so bear with me)!

When I run `dotnet run` within VS Code, I get the following output:

```
PS C:\Users\mgrande\repos\asp-net-core-vue-starter> dotnet run
Hosting environment: Production
Content root path: C:\Users\mgrande\repos\asp-net-core-vue-starter
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
```

Note that it says it's running in Production mode. How do I switch to Development mode?

**Comment by liborpansky** [comment]
Hi, dotnet CLI uses environment variable to set environment when running `dotnet run`. You can read more about it [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1) and find command for your OS. 

For example running on Windows in PowerShell, following commands are used:
```powershell
$Env:ASPNETCORE_ENVIRONMENT = "Development"
dotnet run
```

You can test it:
```powershell
$Env:ASPNETCORE_ENVIRONMENT = "Development"
dotnet run
```
Output:
```
Hosting environment: Development
Content root path: C:\Users\Libor\Source\Repos\asp-net-core-vue-starter
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
```
And set it back to PROD:
```powershell
$Env:ASPNETCORE_ENVIRONMENT = "Production"
dotnet run
```
Output:
```
Hosting environment: Production
Content root path: C:\Users\Libor\Source\Repos\asp-net-core-vue-starter
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
```

**Comment by mattgrande** [comment]
That's perfect, @liborpansky. Thank you!
