### ISSUE TITLE
HMR blocked due to CORS

### ISSUE THREAD

**Issue by arnvanhoutte** [SoftwareAteliers/asp-net-core-vue-starter#35]
I cloned the project from here and didn't really change much. The project builds and starts fine but I saw this error in my dev tools:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://192.168.1.54:8080/sockjs-node/info?t=1589278796344. (Reason: CORS request did not succeed).

The issue is probably caused by the request going to the IP address instead of localhost, but I am not sure where to change this
![image](https://user-images.githubusercontent.com/5654490/81673127-6c615e80-944b-11ea-9c62-fd3cff660c5f.png)

**Comment by liborpansky** [comment]
Hi, you are using vue app URL, not ASP.NET Core app. You should work with http://localhost:5000/

**Comment by arnvanhoutte** [comment]
I just started the app with my IIS Express config, so https://localhost:44352/ in this case

**Comment by liborpansky** [comment]
Try to run the site with http only and let me know if your problem persists :)

**Comment by arnvanhoutte** [comment]
It works with HTTP, but ideally our application should work in HTTPS-mode. I also have an Angular project that uses HMR/Sock-JS and that one uses HTTPS with no issue because it just talks to my localhost, instead to a specific IP

**Comment by liborpansky** [comment]
There were some attempts to support HTTPS in dev environment #24 , but I've actually never seen a working project with ASP.NET / Vue...

**Comment by arnvanhoutte** [comment]
Ah that's too bad. Hopefully someone can figure it out soon
