### ISSUE TITLE
The SPA default page middleware could not return the default page '/index.html' 

### ISSUE THREAD

**Issue by lukee48** [SoftwareAteliers/asp-net-core-vue-starter#37]
cloned and npm build but when running the app I get the following

The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

**Comment by liborpansky** [comment]
After running `npm build` where do you publish the app?

**Comment by lukee48** [comment]
I followed the read me to the letter

1. Cloned
2. npm install
3. dotnet run

Have I missed something?

**Comment by liborpansky** [comment]
When you run `dotnet run` you should receive following output:
```
info: VueCliMiddleware[0]
      Starting server on port 8080...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Libor\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\Projects\GitHub\SoftwareAteliers\asp-net-core-vue-starter
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
> asp-net-core-vue-starter@0.1.0 serve C:\Projects\GitHub\SoftwareAteliers\asp-net-core-vue-starter\ClientApp
> vue-cli-service serve "--port" "8080"
 INFO  Starting development server...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
<s> [webpack.Progress] 0% compiling    
<s> [webpack.Progress] 10% building 0/0 modules 0 active 
...
```

Can you confirm you're running in Development environment?

**Comment by lukee48** [comment]
Sorry, that was exactly my issue.

For some reason, VS code is ignoring my launch settings for Development Mode.

Thanks for that :)

**Comment by liborpansky** [comment]
You can find more info in this issue https://github.com/SoftwareAteliers/asp-net-core-vue-starter/issues/34
