### ISSUE TITLE
Dotnet new template package

### ISSUE THREAD

**Issue by jdebarochez** [SoftwareAteliers/asp-net-core-vue-starter#4]
Hello,

Do you intend to create a Nuget package for this template? It would be neat to scaffold this with `dotnet new vue` as we can do with React and Angular templates.

Here's more info on [how to](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template). I'm forking the project to start digging in. I will submit a PR once finished.

**Comment by liborpansky** [comment]
Sure, great idea! Once finished I'll merge the PR and create a NuGet package 👍

**Comment by liborpansky** [comment]
Thank you!

**Comment by jdebarochez** [comment]
Hello @liborpansky!

In order to install from the Nuget repository with `dotnet new -i SoftwareAteliers.AspNetCoreVueStarter`, we first need to publish the package on Nuget.org. Do you have an account with SoftwareAteliers you want to publish it with?

**Comment by liborpansky** [comment]
Hi @jdebarochez , I've published already two versions. 1.0.0 two days ago and 1.0.1 today in the morning... You can find it on [NuGet](https://www.nuget.org/packages/SoftwareAteliers.AspNetCoreVueStarter/)

**Comment by jdebarochez** [comment]
Ha yes, indeed! My bad, somehow my search in Nuget was not able to find them. Please ignore my previous comment.
