### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by rcholic** [SoftwareAteliers/asp-net-core-vue-starter#41]
I am trying to this starter to create a simple website. My Node and NPM version is:

> node: v14.4.0
> npm: 6.14.5
> dotnet core: 3.1

When I run the starter in VS 8.6.5 (on Mac), I got the following error, which is essentially `env: node: No such file or directory`. What does this error mean and how to fix it? -- Thanks

VueCliMiddleware: Information: Starting server on port 8080...
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.5/Microsoft.AspNetCore.WebSockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
env: node: No such file or directory
info: VueCliMiddleware[0]
      Starting server on port 8080...
VueCliMiddleware: Information: Starting server on port 8080...
env: node: No such file or directory
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.5/Microsoft.AspNetCore.Diagnostics.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:6011
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]

**Comment by liborpansky** [comment]
Hi, I do not use mac, but it seems there are other users having the same problem as you do. 
Solution seems to be uninstall and install node again following this [SO thread](https://stackoverflow.com/questions/43465086/env-node-no-such-file-or-directory-in-mac)
