### ISSUE TITLE
How to achieve Hot Reloading?

### ISSUE THREAD

**Issue by kerry-perret** [SoftwareAteliers/asp-net-core-vue-starter#43]
I've noticed that hot reloading does not work out-of-the-box, that is, how can I enable it?

Thanks for all the good work!

Cheers

**Comment by liborpansky** [comment]
Hi, I guess you used https endpoint? HMR does not work with https, you should use http only.

**Comment by kerry-perret** [comment]
Thanks for pointing this out!
