### ISSUE TITLE
Error with webpack server

### ISSUE THREAD

**Issue by TrungThinh** [SoftwareAteliers/asp-net-core-vue-starter#53]
I clone your project and remove all the contents of the folder /ClientApp, replace with my vuejs source.
After that, and "npm run serves" it appears error:   

./src/main.js in multi (webpack)-dev-server/client?http://172.17.13.174:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js, multi (webpack)/hot/dev-server.js (webpack)-dev-server/client?http://172.17.13.174:8080&sockPath=/sockjs-node ./src/main.js

**Comment by liborpansky** [comment]
Hi, your Vue app has been created using Vue CLI 3+? If you run `npm run serve` and app does not start, it's a problem with your Vue application, it should be able to start with serve as a standalone app, no matter the folder...

**Comment by TrungThinh** [comment]
> Hi, your Vue app has been created using Vue CLI 3+? If you run `npm run serve` and app does not start, it's a problem with your Vue application, it should be able to start with serve as a standalone app, no matter the folder...

thank you, I will check again
