### ISSUE TITLE
MapSpaFallbackRoute 

### ISSUE THREAD

**Issue by hnviradiya** [SoftwareAteliers/asp-net-core-vue-starter#6]
I was following your article and I am having difficulty setting MapSpaFallbackRoute. If this feature is added in this repo, then it will be helpful to many in my opinion.

**Comment by liborpansky** [comment]
Hi, why do you need to set a `SpaFallbackRoute`? This instruction was used by `UseMvc` middleware, but lately has been replaced by `UseSpa` middleware - if you check a [source code](https://github.com/aspnet/JavaScriptServices/blob/7a0413434577274666ff72ee790b53cc71b22970/src/Microsoft.AspNetCore.SpaServices.Extensions/SpaDefaultPageMiddleware.cs), there's already an instruction to rewrite all requests to the default SPA page. You can try it out and call any endpoint of your app and the request, if not found by UseStaticFiles or UseSpaStaticFiles middlewares or does not match any of your API endpoints, will be redirected to default SPA index.html page.

Is there some use case that does not work well for you?

**Comment by hnviradiya** [comment]
Aha. Ok. I am using identityserver hybrid flow. 

And after retrieving claims when it is redirecting to this client project with route "/oidc-client". It says unknown location. (Sample url=> localhost:5000/oidc-client).

Exact error is "Correlation failed: Unknown Location" (it is 500 internal server error)

I noticed that other routes are being handled properly. Only this route has issue. "oidc-client".

It seems this is conflicting with useauthentication middleware. I am not able to figure this out.

**Comment by liborpansky** [comment]
I'm using Identity Server 4 as well with Implicit flow. Do you have some minimal reproduction repository? The problem can be order of middlewares (should be Static Files -> Auth -> MVC -> Spa) or some conflicts with auth middleware... 

Which component throws the error? Did you check a log file of Identity Server? Do you use Identity Server as a separate SSO or it's running on the same app with your API?

**Comment by hnviradiya** [comment]
Hi @liborpansky I have forked your repo and changed in that. (U can refer my last (and first also) commit for changes)
https://github.com/hnviradiya/asp-net-core-vue-starter/blob/master/Startup.cs

For identityserver I was using directly their official repo. So you can use it directly.
https://github.com/IdentityServer/IdentityServer4

I have configured forked repo in the way, it will directly work with above identityserver repo. so both repos will work once clonned and packages restored.

**Comment by liborpansky** [comment]
I was trying to play around with the problem, but I didn't find any cause. 
I also created a clean ASP.NET Core MVC project without front-end frameworks, just to try your IS4 configuration, but **with your settings I couldn't get it to work neither for pure MVC app** without additional modifications. Respectively to the demo configuration of MvcHybridAutomaticRefresh app you are missing `AddAutomaticTokenManagement` middleware.

But generally I can't help you better, I've never set up Hybrid configuration for applications using front-end frameworks. I used either Hybrid client with cookie authorization for MVC apps or, lately, I prefer pure front-end solution with Implicit grant type sending authorization header for each request and manage access token with silent renew by Vue app.

If you have hybrid app with razor views combined with Vue application, you have to find correct configuration yourself, I can't help you better with limited time I have...

**Comment by hnviradiya** [comment]
Yes. So this is being worked there. So I am closing here. And thanks for this article. It was really helpful and leading 😊
