### ISSUE TITLE
HMR?

### ISSUE THREAD

**Issue by hnviradiya** [SoftwareAteliers/asp-net-core-vue-starter#7]
Isn't Hot Module Replacement supported in VueCliMiddleware?
On Change, it builds successfully. But browser is not updated automatically. 
We have to refresh.

**Comment by liborpansky** [comment]
For me HMR works as expected for both `UseVueCli` and `UseProxyToSpaDevelopmentServer`... You're the first one to report this problem.


![ice_video_20190219-174648](https://user-images.githubusercontent.com/9642342/53032126-81308b80-346e-11e9-9e58-5c292dc0cbf1.gif)

**Comment by hnviradiya** [comment]
Hmm. I was also getting some errors related to SignalR (which I ignored that time). i guess that is the issue. Unfortunately I will be available after 5 days to look into code and give you exact information.

**Comment by liborpansky** [comment]
Ok, if you find some template-related problem feel free to open a new issue. For now closing.
